services:
  api:
    build: ./app
    restart: always
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./app/:/opt/projects/app/
      - ./logs/:/opt/projects/app/logs
    ports:
      - 127.0.0.1:8005:8001
    env_file:
      - ./.env/dev.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://localhost:8001/v1/health/ping || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      - db

  db:
    image: postgres:17.4
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ./.env/db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 60s
      timeout: 60s
      retries: 6